# Generated by Django 4.0.5 on 2022-06-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_address_bio_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='', max_length=1000)),
                ('quantity', models.CharField(default='', max_length=1000)),
                ('price', models.CharField(default='', max_length=10000)),
                ('store_name', models.CharField(default='', max_length=10000)),
                ('Pro_ID', models.IntegerField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='UserID',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='address',
            name='my_address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='address',
            name='nationality',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='bio',
            name='Fname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='bio',
            name='UserID',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='bio',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='UserID',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dr_fname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dr_lname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='people',
            name='Fname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='people',
            name='Lname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='people',
            name='UserID',
            field=models.IntegerField(default=''),
        ),
    ]
