# Generated by Django 4.0.5 on 2022-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_address_userid_alter_bio_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='UserID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bio',
            name='UserID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='UserID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='people',
            name='UserID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pro_ID',
            field=models.IntegerField(default=1),
        ),
    ]
