# Generated by Django 4.0.5 on 2022-06-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_address_userid_alter_bio_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Pro_ID',
        ),
    ]
