# Generated by Django 4.0.5 on 2022-06-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_address_userid_remove_bio_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='UserID',
        ),
    ]
