# Generated by Django 4.0.5 on 2022-06-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_people_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='address',
            name='my_address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='address',
            name='nationality',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Fname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dr_fname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dr_lname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='people',
            name='Fname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='people',
            name='Lname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_name',
            field=models.CharField(max_length=10000),
        ),
    ]
