# Generated by Django 4.0.5 on 2022-06-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dr_fname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
    ]
